[build-system]
requires = ["maturin>=1.14.1"]
build-backend = "maturin"

[tool.maturin]
python-source = "."
include = [
    "bcml/assets/scripts/*.js",
    "bcml/assets/help/**/*",
]

[project]
name = "bcml"
version = "3.11.0-a2"
description = "A mod manager for The Legend of Zelda: Breath of the Wild"
author = "NiceneNerd"
author_email = "macadamiadaze@gmail.com"
license = { file = "docs/LICENSE.md" }
dependencies = [
    "aamp>=1.4.1",
    "byml>=2.4.5",
    "botw-utils>=0.2.3",
    "rstb>=1.2.2",
    "oead>=1.3.0a2", # https://github.com/cobra838/oead/releases
    "packaging>=26.2",
    "pythonnet>=3.0.5,<3.1; python_version == '3.9'",
    "pythonnet>=3.1.0; python_version >= '3.10'",
    "PyQt5>=5.15.11; platform_system == 'Linux'",
    "pyqtwebengine>=5.15.7; platform_system == 'Linux'",
    "pywebview==3.7.2",
    "QtPy>=2.4.3; platform_system == 'Linux'",
    "PyYAML>=6.0.3",
    "requests>=2.32.5,<2.34; python_version == '3.9'",
    "requests>=2.34.2; python_version >= '3.10'",
    "xxhash>=3.8.1",
]
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
scripts = { bcml-debug = "bcml.__main__:main_debug" }
gui-scripts = { bcml = "bcml.__main__:main" }

[project.urls]
repository = "https://github.com/cobra838/BCML"
homepage = "https://gamebanana.com/tools/6624"